gainsLog_client/__init__.py
import logging

from flask import Flask, current_app
from flask_login import LoginManager

from gainsLog_client.utility.request_util import RequestUtil
from gainsLog_client.utility.user_util import UserUtil
from gainsLog_client.views import home_view
from gainsLog_client.views import users_view
from gainsLog_client.views import workouts_view

app = Flask(__name__)
app.config['ADD_SIZE'] = 1
app.config['SERVICE_URL'] = "http://localhost:8080"
app.secret_key = 'This for now'

login_manager = LoginManager()
login_manager.init_app(app)
login_manager.login_message = 'Login Required'
login_manager.login_view = 'home_view.root'


@login_manager.user_loader
def load_user(user_id):
    logging.info('user_id: {}'.format(user_id))
    user_d = RequestUtil.get(current_app.config['SERVICE_URL'] + "/users/{}".format(user_id))

    user = UserUtil.map_dict_to_user(user_d)

    user.is_authenticated = True
    user.is_anonymous = False
    user.is_active = True
    return user


@app.after_request
def add_header(r):
    """
    Add headers to both force latest IE rendering engine or Chrome Frame,
    and also to cache the rendered page for 10 minutes.
    """
    r.headers["Cache-Control"] = "no-cache, no-store, must-revalidate"
    r.headers["Pragma"] = "no-cache"
    r.headers["Expires"] = "0"
    r.headers['Cache-Control'] = 'public, max-age=0'
    return r


app.register_blueprint(home_view.mod)
app.register_blueprint(users_view.mod)
app.register_blueprint(workouts_view.mod)


if __name__ == "__main__":
    logging.basicConfig(filename='myapp.log', level=logging.INFO)

gainsLog_client/views/home_view.py
from flask import Blueprint, render_template, request, current_app
from flask_login import login_required, logout_user, login_user, current_user

from gainsLog_client.utility.form_util import FormUtil
from gainsLog_client.utility.json_util import JsonUtil
from gainsLog_client.utility.request_util import RequestUtil
from gainsLog_client.utility.user_util import UserUtil

mod = Blueprint('home_view', __name__, url_prefix='/')


@mod.route("", methods=["GET"])
def root():
    return render_template("index.html")


@mod.route("home", methods=["GET"])
@login_required
def go_home_roger():
    return render_template("home.html", user=current_user)


@mod.route("login", methods=["POST"])
def login():
    if current_user.is_authenticated:
        return render_template("home.html", user=current_user)
    credential = FormUtil.map_form_to_credential(request.form)
    cred_dict = JsonUtil.obj_to_dict(credential)

    user_d = RequestUtil.post(current_app.config['SERVICE_URL'] + "/login", cred_dict)
    user = UserUtil.map_dict_to_user(user_d)

    user.is_authenticated = True
    user.is_anonymous = False
    user.is_active = True
    login_user(user)

    return render_template("home.html", user=user)


@mod.route("logout", methods=["GET"])
@login_required
def logout():
    logout_user()
    return render_template("index.html")

gainsLog_client/views/users_view.py
from flask import Blueprint, render_template, request, current_app
from flask_login import login_required, current_user, login_user, logout_user

from gainsLog_client.utility.form_util import FormUtil
from gainsLog_client.utility.json_util import JsonUtil
from gainsLog_client.utility.request_util import RequestUtil

mod = Blueprint('users_view', __name__, url_prefix='/users')


@mod.route("/<string:userName>", methods=["GET"])
@login_required
def user_detail(userName):
    user = RequestUtil.get(current_app.config['SERVICE_URL'] + "/users/{}".format(userName))
    return render_template("profile.html", user=user)


@mod.route("/", methods=["POST"])
def create_user():
    new_user = FormUtil.map_form_to_user(request.form)
    user_dict = JsonUtil.obj_to_dict(new_user)
    user = RequestUtil.post(current_app.config['SERVICE_URL'] + "/users/", user_dict)

    user.is_authenticated = True
    user.is_anonymous = False
    user.is_active = True
    login_user(user)

    return render_template("home.html", user=current_user)


@mod.route("/<string:userName>", methods=["DELETE"])
@login_required
def delete_user(userName):
    RequestUtil.delete(current_app.config['SERVICE_URL'] + "/users/{}".format(userName))
    logout_user()
    return render_template("index.html")


@mod.route("/<string:userName>", methods=["POST"])
@login_required
def update_user(userName):
    user = FormUtil.map_form_to_user(request.form)
    user_dict = JsonUtil.obj_to_dict(user)
    RequestUtil.post(current_app.config['SERVICE_URL'] + "/users/{}".format(userName), user_dict)
    return render_template("profile.html", user=current_user)

gainsLog_client/views/workouts_view.py
from flask import Blueprint, render_template, request, current_app
from flask_login import login_required, current_user

from gainsLog_client.utility.form_util import FormUtil
from gainsLog_client.utility.json_util import JsonUtil
from gainsLog_client.utility.request_util import RequestUtil

mod = Blueprint('workouts_view', __name__, url_prefix='/users/<string:userName>/workouts')


@mod.route("/", methods=["GET"])
@login_required
def get_workouts(userName):
    workouts = RequestUtil.get(current_app.config['SERVICE_URL'] + "/users/{}/workouts".format(userName))
    return render_template("workouts.html", user=current_user, workouts=workouts, default_add_size=current_app.config['ADD_SIZE'])


@mod.route("/", methods=["POST"])
@login_required
def create_workout(userName):
    workout = FormUtil.map_form_to_workout(request.form, userName)
    workout_json = JsonUtil.obj_to_dict(workout)
    RequestUtil.post(current_app.config['SERVICE_URL'] + "/users/{}/workouts".format(userName), workout_json)
    return get_workouts(workout.get_userName())


@mod.route("/<string:name>", methods=["GET"])
@login_required
def workout_detail(userName, name):
    workout = RequestUtil.get(current_app.config['SERVICE_URL'] + "/users/{}/workouts/{}".format(userName, name))
    return render_template("workout_detail.html", user=current_user, workout=workout)


@mod.route("/<string:name>", methods=["POST"])
@login_required
def workout_update(userName, name):
    workout = FormUtil.map_form_to_workout(request.form, name)
    workout_json = JsonUtil.obj_to_dict(workout)
    workout = RequestUtil.post(current_app.config['SERVICE_URL'] + "/users/{}/workouts/{}".format(userName, name), workout_json)
    return render_template("workout_detail.html", user=current_user, workout=workout)


@mod.route("/<string:name>", methods=["DELETE"])
@login_required
def workout_delete(userName, name):
    RequestUtil.delete(current_app.config['SERVICE_URL'] + "/users/{}/workouts/{}".format(userName, name))
    return get_workouts()

gainsLog_client/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Home</title>
</head>
<body>
{% include 'nav_bar.html' %}
Home Page
</body>
</html>

gainsLog_client/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="/static/base.css" />
    <link rel="stylesheet" href="/static/index.css" />
    <title>Gains Log</title>
</head>
<body>
    <div id="container">
        <div id="login-div">
            <form action="/login" id="login-form" method="POST" name="login">
                <label><b>Username</b></label>
                <input type="text" placeholder="Enter Username" name="cred-eman" required>

                <label><b>Password</b></label>
                <input type="password" placeholder="Enter Password" name="cred-drowssap" required>

                <button type="submit">Login</button>
            </form>
        </div>
        <div id="signup-div">
            <form action="/users/" id="create-user-form" method="POST" name="create-user">
                <label><b>Email</b></label>
                <input type="email" placeholder="Enter Email" name="user-email" required>

                <label><b>Username</b></label>
                <input type="text" placeholder="Enter Username" name="user-name" required>

                <label><b>Password</b></label>
                <input type="password" placeholder="Enter Password" name="user-password" required>

                <label><b>Confirm Password</b></label>
                <input type="password" placeholder="Confirm Password" name="user-confirm" required>

                <button type="submit">Register</button>
            </form>
        </div>
    </div>
</body>
</html>

gainsLog_client/templates/nav_bar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="/static/base.css" />
    <link rel="stylesheet" href="/static/nav_bar.css" />
</head>
<body>
    <nav>
        <div id="nav-bar">
            <ul>
                <li><a href="/home">Home</a></li>
                <li><a href="/users/{{user.name}}">Profile</a></li>
                <li><a href="/users/{{user.name}}/workouts/">Workouts</a></li>
                <li><a href="#">Stats</a></li>
                <li><a href="#">Calendar</a></li>
                <li style="float:right"><a href="#about">About</a></li>
                <li style="float:right"><a href="/logout" >Logout</a></li>
            </ul>
        </div>
    </nav>
<br/>
<br/>
<br/>
</body>
</html>

gainsLog_client/templates/profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <script type="text/javascript" src="{{ url_for('static', filename='request_manager.js') }}"></script>
    <link rel="stylesheet" href="/static/profile.css" />
</head>
<body>
{% include 'nav_bar.html' %}
<div id="container">
    <div id="info-div">
        <ul id="info-list">
          <li>{{user.name}}</li>
            <br/>
          <li>{{user.email}}</li>
        </ul>
    </div>
    <div id="update-div">
        <form action="/users/{{user.name}}" id="update-user-form" method="POST" name="update-user">
            <label><b>Email</b></label>
            <input type="email" placeholder="Enter Email" name="user-email" required>

            <label><b>Username</b></label>
            <input type="text" placeholder="Enter Username" name="user-name" required>

            <label><b>Password</b></label>
            <input type="password" placeholder="Enter Password" name="user-password" required>

            <label><b>Confirm Password</b></label>
            <input type="password" placeholder="Confirm Password" name="user-confirm" required>

            <button type="submit">Update</button>
        </form>
    </div>
</div>

</body>
</html>

gainsLog_client/templates/workout_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <script type="text/javascript" src="{{ url_for('static', filename='request_manager.js') }}"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='add_row.js') }}"></script>
</head>
<body>
{% include 'nav_bar.html' %}
<form action="/users/{{user.name}}/workouts/{{workout.name}}" id="updateForm" method="POST" name="update">
        <table id="updateTable">
            <caption><input type="text" name="wk-name" id="update-workout-name" value="{{workout.name}}"></caption>
            <thead>
            <tr>
                <th>Exercise Name</th>
                <th>Weight x Reps</th>
                <th>Weight x Reps</th>
                <th>Weight x Reps</th>
                <th>Weight x Reps</th>
                <th>Weight x Reps</th>
                <th>Muscle Group</th>
            </tr>
            </thead>
            {% for exercise in workout.exercises %}
            <tr>
                <td><input type="text" name="ex-name" value="{{exercise.name}}"/></td>
                {% for set in exercise.sets %}
                <td><input type="text" name="st-{{loop.index}}-wgt" value="{{set.weight}}" size="5"/><input type="text" name="st-{{loop.index}}-rps" value="{{set.reps}}" size="5"/></td>
                {% endfor %}
                <td>
                    <input list="muscle-groups" name="muscle-group" value="{{exercise.muscleGroup}}"/>
                    <datalist id="muscle-groups">
                        <option value="Arms">
                        <option value="Back">
                        <option value="Chest">
                        <option value="Core">
                        <option value="Heart">
                        <option value="Legs">
                        <option value="Shoulders">
                    </datalist>
                </td>
            </tr>
            {% endfor %}
        </table>
        <div class=keyDiv id="addCreateDiv">
            <button class=keyButtonL id="addRowButton" onclick="addRow('updateTable'); return false;">Add Exercise</button>
            <button class=keyButtonR id="updateWorkoutButton" onclick="document.update.submit()">Update Workout</button>
        </div>
    </form>
</body>
</html>

gainsLog_client/templates/workouts.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="An app to track your workouts">
    <meta name="author" content="Sheldon Lee Hampton II">
    <script type="text/javascript" src="{{ url_for('static', filename='request_manager.js') }}"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='add_row.js') }}"></script>
    <title>Fitness Tracker</title>
</head>

<body>
{% include 'nav_bar.html' %}

<div class="container">
    {% for workout in workouts %}
    <table>
        <caption>{{workout.name}}</caption>
        <thead>
        <tr>
            <th>Exercise Name</th>
            <th>Weight x Reps</th>
            <th>Weight x Reps</th>
            <th>Weight x Reps</th>
            <th>Weight x Reps</th>
            <th>Weight x Reps</th>
            <th>Muscle Group</th>
        </tr>
        </thead>
        <tbody>
        {% for exercise in workout.exercises %}
        <tr>
            <td>{{exercise.name}}</td>
            {% for set in exercise.sets %}
            <td>{{set.weight}} x {{set.reps}}</td>
            {% endfor %}
            <td>{{exercise.muscleGroup}}</td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
      <div class=keyDiv id="editRemoveDiv">
        <button class=keyButtonL id="editButton" onclick="request('GET', '{{ url_for('workouts_view.workout_detail', userName=user.name, name=workout.name) }}'); ">Edit Workout</button>
        <button class=keyButtonR id="removeButton" onclick="request('DELETE', '{{ url_for('workouts_view.workout_detail', userName=user.name, name=workout.name) }}'); window.location.reload();">Remove Workout</button>
      </div>
    <br/>
    <br/>
    <br/>
    {% endfor %}

    <br/>
    <form action="/users/{{user.name}}/workouts/" id="createForm" method="POST" onsubmit="setTimeout(function () { window.location.reload(); }, 10)" name="create">
        <table id="createTable">
            <caption><input type="text" name="wk-name" id="create-workout-name"></caption>
            <thead>
            <tr>
                <th>Exercise Name</th>
                <th>Weight x Reps</th>
                <th>Weight x Reps</th>
                <th>Weight x Reps</th>
                <th>Weight x Reps</th>
                <th>Weight x Reps</th>
                <th>Muscle Group</th>
            </tr>
            </thead>
            {% for x in range(default_add_size) %}
            <tr>
                <td><input type="text" name="ex-name" placeholder="name" /></td>
                <td><input type="text" name="st-1-wgt" placeholder="set 1 wgt" size="5"/><input type="text" name="st-1-rps" placeholder="set 1 rps" size="5"/></td>
                <td><input type="text" name="st-2-wgt" placeholder="set 2 wgt" size="5"/><input type="text" name="st-2-rps" placeholder="set 2 rps" size="5"/></td>
                <td><input type="text" name="st-3-wgt" placeholder="set 3 wgt" size="5"/><input type="text" name="st-3-rps" placeholder="set 3 rps" size="5"/></td>
                <td><input type="text" name="st-4-wgt" placeholder="set 4 wgt" size="5"/><input type="text" name="st-4-rps" placeholder="set 4 rps" size="5"/></td>
                <td><input type="text" name="st-5-wgt" placeholder="set 5 wgt" size="5"/><input type="text" name="st-5-rps" placeholder="set 5 rps" size="5"/></td>
                <td>
                    <input list="muscle-groups" name="muscle-group" />
                    <datalist id="muscle-groups">
                        <option value="Arms">
                        <option value="Back">
                        <option value="Chest">
                        <option value="Core">
                        <option value="Heart">
                        <option value="Legs">
                        <option value="Shoulders">
                    </datalist>
                </td>
            </tr>
            {% endfor %}
        </table>
        <div class=keyDiv id="addCreateDiv">
            <button type="button" class=keyButtonL id="addRowButton" onclick="addRow('createTable'); return false;">Add Exercise</button>
            <button type="button" class=keyButtonR id="createWorkoutButton"  onclick="document.create.submit()">Create Workout</button>
        </div>
    </form>
</div>

<footer class="footer">
</footer>

</body>
</html>